name:                crud-generator
version:             0.1.0.0
github:              "github.com/natani3l"
license:             BSD3
author:              "Nataniel Siebeneichler"
maintainer:          "nataniel.lemes@estudante.uffs.edu.br"
copyright:           "2023 Nataniel Siebeneichler"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/crud-generator#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- monad-logger
- mtl
- persistent
- persistent-sqlite
- persistent-template
- servant-server
- text
- time
- transformers
- wai
- warp
- directory
- bytestring
- template-haskell
- containers
- filepath
- network

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  api:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - crud-generator

tests:
  main-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - crud-generator
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
